TITLE "Feral - 「第1回 JAZZ ART せんがわ」に於いて収録"
PERFORMER "JAZZ ART TRIO"
REM GENRE "Jazz"
REM DATE "2008-07-19"
REM DISCID 020C4601
FILE "JAZZ ART TRIO - Feral - 「第1回 JAZZ ART せんがわ」に於いて収録.flac" WAVE
  TRACK 01 AUDIO
    TITLE "Feral"
    PERFORMER "JAZZ ART TRIO"
    INDEX 01 00:00:00
