TITLE "Skylarking - COLIN'S NON-ALBUM WORK TAPES"
PERFORMER "XTC"
REM GENRE "Rock"
REM DATE "2016"
FILE "XTC - Skylarking - COLIN'S NON-ALBUM WORK TAPES.flac" WAVE
  TRACK 01 AUDIO
    TITLE "Halley's Comet"
    PERFORMER "XTC"
    INDEX 01 00:00:00
  TRACK 02 AUDIO
    TITLE "Find The Fox"
    PERFORMER "XTC"
    INDEX 01 02:37:11
